### ISSUE TITLE
Fix failing CI

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/bubblewrap#12]
CI failing in this [this](https://github.com/TechWiz-3/bubblewrap/actions/runs/3272662588/jobs/5383944303) superlinter run, please solve the issues and make a PR.

**Comment by aaaandrzej** [comment]
This should be fixed now, [#13 ] is merged. Thanks for a fast review, btw.

**Comment by TechWiz-3** [comment]
❤️
