### ISSUE TITLE
Automated releases to Pypi (on workflow dispatch)

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/bubblewrap#2]

**Comment by coldenate** [comment]
Hi there! I have done this workflow in the past. I may be able to help. Would you assign me this issue, @TechWiz-3?

**Comment by TechWiz-3** [comment]
Go ahead :)

**Comment by coldenate** [comment]
Thank you!

**Comment by coldenate** [comment]
@TechWiz-3, would you prefer the uploading to happen when you create a GitHub release?

**Comment by TechWiz-3** [comment]
That works 👍

**Comment by coldenate** [comment]
I created the PR! The workflow will run on dispatch and on Github Release.
