### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/bubblewrap#4]

**Comment by aloner-pro** [comment]
Which one should be used here `pylink` or `flake8` or others?

**Comment by TechWiz-3** [comment]
`flake8` please 🙏

**Comment by aloner-pro** [comment]
Done. So could you assign me this.

**Comment by TechWiz-3** [comment]
Sure :)

**Comment by TechWiz-3** [comment]
Repo has been linted however this issue will remain open until linting is added to the CI 👍
