### ISSUE TITLE
Add support for NerdFont arrows

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/bubblewrap#5]
Commonly used in ZSH themes. Allow a similar function to create text with arrows like so:
<img width="376" alt="Screen Shot 2022-10-12 at 11 37 41 am" src="https://user-images.githubusercontent.com/75515581/195222997-41a0444e-97c3-4a93-940e-60f0fd9b5d49.png">

The icon can be found [here](https://www.nerdfonts.com/cheat-sheet) under the query `arrow` and is at the very bottom of the search. It looks like this:

<img width="184" alt="Screen Shot 2022-10-12 at 11 36 12 am" src="https://user-images.githubusercontent.com/75515581/195222835-d26ff283-1195-4e53-8eb9-3cda2b6fc86b.png">

**Comment by zluipaiva** [comment]
hello, I would like to work on this issue

**Comment by TechWiz-3** [comment]
Go ahead :)
