### ISSUE TITLE
Want to update README.md file and adding CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by sb-decoder** [TechWiz-3/bubblewrap#6]
@TechWiz-3 Can I do this?
I want to add how to contribute section and also contributors profile into main README.md file

**Comment by TechWiz-3** [comment]
Go ahead :), I'd appreciate it if you could copy the contribution guidelines from my `happy-jar-cli` or `who-unfollowed-me` project 🙏

**Comment by sb-decoder** [comment]
@TechWiz-3 please check the PR , and tell me if you want any changes
